### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by teatkin** [rahiel/giternity#5]
I am attempting to package giternity for OpenBSD but I need some sort of source archive in order to be able to do so. Would you be able to create a 0.4 release such that I can do this? 

Thank you
Tom

**Comment by rahiel** [comment]
Hey Tom, thanks for packaging this.

The releases are published at: https://pypi.org/project/giternity/#files. Can you work with that `giternity-0.4.tar.gz` file?

**Comment by teatkin** [comment]
Hi Rahiel,

Apologies for not seeing this until now, apparently I'm not particularly observant!
I've since stopped using OpenBSD and so I don't know if the port ever got finished, but I'm still a big user on my Debian server.

Thanks,
Tom
